# “Suspicious Order Monitoring” Compliance Application {Comply with SOM}

## The Problem.

The opioid crisis has become a top public health priority in the US. It has resulted in many lost lives, increased crime and poverty, as well as depletion of government resources including police, hospitals, rehabilitation centers and tax dollars. The U.S. Drug Enforcement Agency (DEA) has implemented an enforcement tool called the Suspicious Order Monitoring (SOM) requirement as a means to address the opioid crisis. SOM requires that any DEA-registered entity that distributes opioids, or other controlled substances, must design and operate a system that discloses suspicious orders of controlled substances.
The DEA has not provided exact guidelines on how to identify suspicious orders, so it falls on the distributors to create a model and process that flags and reports suspicious transactions. This presents a serious problem for the distributors because revenue is sacrificed when legitimate orders are blocked, and risks are escalated when orders from pharmacies involved in illegal activity are fulfilled.  If found guilty of fulfilling illegitimate orders, distributors can be hit with large fines, or even worse, lose their license to distribute controlled substances. <Name of your product> will help pharmaceutical drug distributors lower these risks, while minimizing the opportunity cost of lost revenue.

## The Solution.

<My application> will be used by the distributors. This application will implement an algorithm that will classify orders as one of three possibilities: “legitimate”, “suspicious”, or “undetermined”. “Legitimate” orders will be executed. “Suspicious” orders will be automatically sent to the DEA. “Undetermined” orders will be manually reviewed by a compliance employee at the organization. The algorithm will rely on the distributor’s data as well as publically available data related to the prevalence of drug use and location of overdoses. Suspicious orders will be identified using metrics that calculate if an order is of unusual size, unusual frequency, located in an area with high rates of abuse and overdoses, or deviates from normal patterns. 

The application will have an interface that will allow the user to connect to the company's internal sales database and map data fields to each variable required for the algorithm. Distributors typically have a team of database administrators that I will be able to assist with the mapping process. The application will also have an interface from which manual review can be conducted, allowing the reviewer to manually flag “undetermined” orders as “legitimate” or “suspicious”. This application can be set to run as often as the user wishes, and will return the calculated classifier for each order to the database from which it came.

## The Result.

Once this application is rolled out to entities that distribute controlled substances, these distributors will be maximizing their revenue by fulfilling almost all legitimate orders they receive and are capable of fulfilling. In addition, I anticipate that no distributors using <product name> will be investigated by the DEA for completing fraudulent orders, if they follow the recommendations of the algorithm. The algorithm will not always be perfect, but I believe the DEA will be forgiving of distributors that only make a few small errors. The team will also establish a process where a portion of the customers send us their data, enabling us to continuously improve the predicative algorithm.

I also proposed a manual review element to the process that accompanies <the product>. Manual review can be prone to mistakes and it is important that these distributors implement a standardized review process in order to obtain consistent results. In the end, <the product> will allow distributors to achieve operational efficiency while they comply with the SOM requirements enforced by the DEA. If the SOM requirements effectively address the opioid crisis that impacts all of us in one way or another, then I will be proud that <the  product> will be a part of that.
